version: 2

models:
  - name: fct_order_fulfillment
    columns:
      - name: order_item_id
        tests:
          - not_null
          - unique

      - name: order_id
        tests:
          - not_null

      - name: product_id
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_products')
                field: product_id

      - name: seller_id
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_seller')
                field: seller_id

      - name: customer_location_id
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_customer_location')
                field: customer_location_id

      - name: delivery_sla_status
        tests:
          - accepted_values:
              arguments:
                values: ['ON_TIME', 'LATE', 'UNKNOWN']